FROM ubuntu

RUN apt-get upgrade && apt-get install \
python3 \

##########ADD PYTHON PACKAGES HERE:#######################

RUN pip install --upgrade Cython

RUN pip install attrdict python-gnupg web3

RUN pip install numpy

RUN pip install pandas

RUN pip install geopy

RUN pip install  scipy

RUN pip install sklearn

RUN pip install keras


RUN cp /usr/bin/python3.6 /usr/bin/python3

COPY src /app

#RUN SCONE_MODE=sim SCONE_HASH=1 SCONE_HEAP=1G SCONE_ALPINE=1		    \
#	&& mkdir conf							    \
#	&& scone fspf create fspf.pb 					    \
#	&& scone fspf addr fspf.pb /  --not-protected --kernel /            \
#	&& scone fspf addr fspf.pb /usr --authenticated --kernel /usr       \
#	&& scone fspf addf fspf.pb /usr /usr 			            \
#	&& scone fspf addr fspf.pb /bin --authenticated --kernel /bin       \
#	&& scone fspf addf fspf.pb /bin /bin 			            \
#	&& scone fspf addr fspf.pb /lib --authenticated --kernel /lib       \
#	&& scone fspf addf fspf.pb /lib /lib 			            \
#	&& scone fspf addr fspf.pb /etc --authenticated --kernel /etc       \
#	&& scone fspf addf fspf.pb /etc /etc 			            \
#	&& scone fspf addr fspf.pb /sbin --authenticated --kernel /sbin     \
#	&& scone fspf addf fspf.pb /sbin /sbin 			            \
#	&& scone fspf addr fspf.pb /signer --authenticated --kernel /signer \
#	&& scone fspf addf fspf.pb /signer /signer 			    \
#	&& scone fspf addr fspf.pb /app --authenticated --kernel /app 	    \
#	&& scone fspf addf fspf.pb /app /app 				    \
#	&& scone fspf encrypt ./fspf.pb > /conf/keytag 			    \
#	&& MRENCLAVE="$(SCONE_HASH=1 python)"			            \
#	&& FSPF_TAG=$(cat conf/keytag | awk '{print $9}') 	            \
#	&& FSPF_KEY=$(cat conf/keytag | awk '{print $11}')		    \
#	&& FINGERPRINT="$FSPF_KEY|$FSPF_TAG|$MRENCLAVE"			    \
#	&& echo $FINGERPRINT > conf/fingerprint.txt			    \
#	&& printf "\n########################################################\nMREnclave: $FINGERPRINT\n########################################################\n\n"


##########CHANGE ENTRYPOINT HERE:#######################
ENTRYPOINT unzip -o /iexec_in/$DATASET_FILENAME -d /iexec_in && python3 /app/main.py
